import Head from 'next/head'
import {BsGrid,BsSearch} from "react-icons/bs";
import Footer from './footer/footer';
import {useRef} from 'react'
import { useRouter } from 'next/router';


export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;


    if(!term) return;

    router.push(`/search?term=${term}`)

  }
  return (
  <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Goblog search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <header className='flex w-full p-5  text-gray-700'>
        {/* right */}
        <div className='flex space-x-4 items-center ml-auto text-lg'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
          {/* avatar */}
          <div className='hover:bg-gray-100 rounded-full'>
          <BsGrid className='h-10 w-10 p-2  '/>
          </div>
        </div>

      </header>

      {/* body */}
      <form className='flex flex-col items-center mt-44 flex-grow w-4/5'>
        <h1 className='text-6xl lg:text-8xl font-semibold text-blue-600'>Go<span className='text-green-500'>blo<span className='font-serif '>g</span></span></h1>
        <div className='flex w-full  mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 item-center sm:max-w-xl lg:max-w-2xl'>
          <BsSearch className='h-5 mr-3 text-gray-500 cursor-pointer' onClick={search} />
          <input ref={searchInputRef} type="text" className='focus:outline-none flex-grow '/>
        </div>
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button onClick={search} className='btn'>Goblog Search</button>
          <button onClick={search} className='btn'>I'm feeling lucky</button>
        </div>
      </form>



      {/* footer */}
      <Footer/>
      </div>
  )
}
